# Generated by Django 5.1.2 on 2024-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbook',
            name='notebook',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='labbook',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
